# Generated by Django 4.2.3 on 2023-07-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=20)),
                ('EmployeeDepartment', models.CharField(blank=True, max_length=20, null=True)),
                ('Country', models.CharField(blank=True, max_length=20, null=True)),
                ('Salary', models.IntegerField(blank=True)),
            ],
        ),
    ]
